"""
Gen-CareerRaceInfo.py - generate careerraceinfo_defaults.sql from CareerInfo.bin.

CareerRaceInfo_NFS1 defines the actual career: which track each of the 328 career races
runs on, lap count, traffic/AI, the goal, and the two reward choices. There is NO seed data
for it anywhere on the OEM media - only the CREATE TABLE and the stored procs. On a real
cabinet the installer runs

    UndergroundGVR.exe -initializeplustabledata

whose GvrCareerInfoManager::PopulatePLUS reads C\\Underground\\CareerInfo.bin and pushes the
rows in via SP_InsertOrUpdate_CareerRaceInfo_NFS1. The portable installer ships a pre-seeded
game.db and never runs the game, so the table is empty - and both the game and the shell look
races up with
    SELECT TOP 1 * FROM CareerRaceInfo_NFS1 WHERE CareerNumber=? AND CareerRaceNumber=?
so an empty table means career mode has no race to configure. Same failure shape as the
empty CarConfiguration_NFS1 (white cars) and empty GlobalVariable (race replays forever).

Parsing CareerInfo.bin directly is preferred over running the game: it is deterministic and
reproducible on any machine.

FILE FORMAT (verified against the shipped 132,512-byte file: 328 records x 404 bytes)

    off  type      column
    ---  --------  ---------------------------------------------
      0  int32     CareerNumber        1..4
      4  int32     CareerRaceNumber    1..82
      8  int32     TrackNumber         1001..1308
     12  int32     TrackDirection      0/1
     16  int32     LapCount            1..9
     20  int32     TrafficDensity      0/2/3
     24  int32     AICarCount          0..7
     28  int32     RequirementType     0..2
     32  int32     RequirementValue    seconds, or 0
     36  int32     RewardType          0/1
     40  int32     RewardCategory      0..17
     44  char[16]  RaceDesc            'Circuit' / 'Sprint' / 'Drag' ...
     60  char[64]  TrackDesc           'The Beginning', '1st Ave Truck Stop' ...
    124  char[128] GoalDesc            'Pick your car. You have 3:45 to finish 3 laps...'
    252  char[48]  RewardTitle         'Window Tint'
    300  char[48]  RewardDesc1         'Light Black Window Tint'
    348  char[48]  RewardDesc2         'Light Green Window Tint'
    396  int32     Choice1             reward item id for RewardDesc1
    400  int32     Choice2             reward item id for RewardDesc2

Cross-checks that confirm the mapping rather than assume it: record 0 has LapCount=3 with
GoalDesc '...3 laps...' and RequirementValue=225 == 3:45; record 1 has RequirementValue=150
== 2:30. Strings are NUL-terminated and every byte after the terminator is zero (verified
across all 328 records), so the field widths are exact.

Usage:  python Gen-CareerRaceInfo.py [CareerInfo.bin] [out.sql]
"""
import os
import struct
import sys

REC = 404
NUM_FIELDS = [
    ('CareerNumber', 0), ('CareerRaceNumber', 4), ('TrackNumber', 8),
    ('TrackDirection', 12), ('LapCount', 16), ('TrafficDensity', 20),
    ('AICarCount', 24), ('RequirementType', 28), ('RequirementValue', 32),
    ('RewardType', 36), ('RewardCategory', 40), ('Choice1', 396), ('Choice2', 400),
]
STR_FIELDS = [
    ('RaceDesc', 44, 16), ('TrackDesc', 60, 64), ('GoalDesc', 124, 128),
    ('RewardTitle', 252, 48), ('RewardDesc1', 300, 48), ('RewardDesc2', 348, 48),
]
# Matches the other seeded tables; the cabinet stamps its own values at runtime.
CREATION_DATE = '1/13/2006 5:37:46 PM'


def cstr(rec, off, width):
    raw = rec[off:off + width]
    z = raw.find(b'\x00')
    if z >= 0:
        raw = raw[:z]
    return raw.decode('latin-1')


def sq(s):
    return "'" + s.replace("'", "''") + "'"


def records(path):
    data = open(path, 'rb').read()
    if len(data) % REC:
        raise SystemExit('%s is %d bytes, not a multiple of %d - unexpected format'
                         % (path, len(data), REC))
    for i in range(len(data) // REC):
        rec = data[i * REC:(i + 1) * REC]
        row = {n: struct.unpack_from('<i', rec, o)[0] for n, o in NUM_FIELDS}
        row.update({n: cstr(rec, o, w) for n, o, w in STR_FIELDS})
        yield i, row


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(here), 'C', 'Underground', 'CareerInfo.bin')
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        here, 'careerraceinfo_defaults.sql')

    cols = (['CareerRaceInfoId', 'CreationDate', 'ModifiedDate', 'PropagationDate', 'CabinetId']
            + [n for n, _ in NUM_FIELDS] + [n for n, _, _ in STR_FIELDS])

    lines = ['-- generated by Tools/Gen-CareerRaceInfo.py from CareerInfo.bin - do not edit',
             '-- %d career race definitions (CareerNumber 1-4)' % (os.path.getsize(src) // REC),
             'DELETE FROM CareerRaceInfo_NFS1;']
    n = 0
    for i, r in records(src):
        vals = ([str(i + 1), sq(CREATION_DATE), '0', '0', '0']
                + [str(r[c]) for c, _ in NUM_FIELDS]
                + [sq(r[c]) for c, _, _ in STR_FIELDS])
        lines.append('INSERT INTO CareerRaceInfo_NFS1 (%s) VALUES (%s);'
                     % (','.join(cols), ','.join(vals)))
        n += 1
    lines.append('')
    with open(out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines))
    print('wrote %s (%d rows) from %s' % (out, n, src))


if __name__ == '__main__':
    main()
